### PR TITLE
feat: update remark version to v11(#32)

### PR DESCRIPTION
**Pull request by Chersquwn**

### CODE REVIEW

**Comment by DanielSWolf** [comment]
Could you please merge this and make a new release? We're having trouble with #32, and this PR would fix it.

**Comment by xiaoxiangmoe** [comment]
@gucong3000 Could you please merge this and make a new release?  Thanks.

**Comment by Evalon** [comment]
@ai can you help with this?
I am not sure that @gucong3000 is still maintain postcss (stylelint) plugins :(

**Comment by ai** [comment]
I don’t have access to npm for this module, but I will try to send him email. Unfortuantelly, it could not help.

**Comment by AlexWayfer** [comment]
We need for more collaborators here.

**Comment by AlexWayfer** [comment]
I even don't know how to use `Chersquwn/postcss-markdown` fork as indirect dependency of `stylelint`.

**Comment by xiaoxiangmoe** [comment]
@gucong3000 thanks

**Comment by hipstersmoothie** [comment]
@gucong3000 could we also get a release for this? Right now I have to hand edit lock files for the types to work!

I'd highly suggest setting up something like https://github.com/intuit/auto or https://github.com/semantic-release/semantic-release so you don't have to get this requested of you again  <3

**Comment by hipstersmoothie** [comment]
Temporary fix (if you're using yarn) until this PR is released:

```json
{
 "resolutions": {
    "postcss-markdown": "https://github.com/gucong3000/postcss-markdown"
  },
}
```

**Comment by ai** [comment]
Sorry, I have no access to GitHub to update version in `package.json`.

**Comment by xiaoxiangmoe** [comment]
@hipstersmoothie it seems ci fails. 
https://travis-ci.org/gucong3000/postcss-syntaxes/builds/630926826?utm_source=github_status&utm_medium=notification

ci environment repo: https://github.com/gucong3000/postcss-syntaxes

**Pull request merged**
